# Generated by Django 4.2.14 on 2024-08-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('link', models.URLField()),
                ('label', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('keyword', models.TextField()),
            ],
        ),
    ]
