# Generated by Django 4.2.14 on 2024-08-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_article'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='NewsArticle',
        ),
    ]
