# Generated by Django 4.2.14 on 2024-08-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_article_newsarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='date_time',
            field=models.DateField(),
        ),
    ]
