# Generated by Django 4.2.14 on 2024-08-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_newsarticle_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
